# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
