# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0004_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
